#!/usr/bin/env bash

op=$( echo -e " Poweroff\n Reboot\n Suspend\n Hibernate\n Logout" | rofi -dmenu | awk '{print tolower($2)}' )

case $op in 
        poweroff)
                ;&
        reboot)
                ;&
        suspend)
                ;&
        hibernate)
                systemctl $op
                ;;
        logout)
                swaymsg exit
                ;;
esac
