#!/usr/bin/env bash

op=$((bluetoothctl devices | awk '{print $2 " " $3 " " $4}' ; ) | cat |  
    tofi -c /home/baum/.config/tofi/clipboardconfig | awk '{print ($1)}')
if [[ -z "$op" ]]; then
    exit
fi
connected=$(bluetoothctl devices Connected | grep $op)
status=""
#check if connected returns something
if [[ -z "$connected" ]]; then
    #if not connected, try to connect
    bluetoothctl connect $op
    status="connected"
else
    #if connected, disconnect
    bluetoothctl disconnect $op
    status="disconnected"
fi
