#!/usr/bin/env bash

op=$( echo -e " Poweroff\n Reboot\n Suspend\n Hibernate\n Lock\n Logout" | wofi --xoffset 0 --yoffset 0 --width 250 --height 270 -i --dmenu | awk '{print tolower($2)}' )

case $op in 
        poweroff)
                ;&
        reboot)
                ;&
        suspend)
                ;&
        hibernate)
                systemctl $op
                ;;
        lock)
		        swaylock
                ;;
        logout)
                swaymsg exit
                ;;
esac
