#!/usr/bin/sh

# small power menu using rofi, i3, systemd and pm-utils
# (last 3 dependencies are adjustable below)
# tostiheld, 2016

lock_command="swaylock"
poweroff_command="systemctl poweroff"
reboot_command="systemctl reboot"
logout_command="swaymsg exit"
suspend_command="systemctl suspend"

# you can customise the rofi command all you want ...
rofi_command="wofi" 

options=$'Lock Screen\nPower Off\nReboot\nLogout\nSuspend' 

# ... because the essential options (-dmenu and -p) are added here
eval \$"$(echo "$options" | $rofi_command --dmenu -P "")_command"
#make selected option execute

