#!/usr/bin/env bash

op=$(( acpi --battery ; echo "CPU Usage: "$[100-$(vmstat 1 1|tail -1|awk '{print $15}')]"%" ; 
cat /proc/meminfo | sed -n '2 p' ; volume=$(pactl list sinks | sed -n '10 p' | awk '{print $5}'); 
echo "Volume: $volume") | cat |  
    wofi --width 500 --height 270 -i --dmenu | awk '{print tolower($2)}')
